In [8]:
def my_pca(A):
    
    T = 1000
    A_copy = A.copy()
    r, c = A_copy.shape

    V = np.random.random_sample((r, r))

    for i in range(T):
        n, m = V.shape
        R = V.copy()
        Q = np.eye(n)

        for k in range(m-1):
            x = np.zeros((n, 1))
            x[k:, 0] = R[k:, k]
            v = x
            v[k] = x[k] + np.sign(x[k,0]) * np.linalg.norm(x)

            s = np.linalg.norm(v)
            if s != 0:
                u = v / s
                R -= 2 * np.dot(u, np.dot(u.T, R))
                Q -= 2 * np.dot(u, np.dot(u.T, Q))
        Q = Q.T
        V = np.dot(A_copy, Q)
    #Q, R = qr(V)
    mv, nv = V.shape
    R = V.copy()
    Q = np.eye(nv)
    
    for k in range(mv-1):
        x = np.zeros((nv, 1))
        x[k:, 0] = R[k:, k]
        v = x
        v[k] = x[k] + np.sign(x[k,0]) * np.linalg.norm(x)
        s = np.linalg.norm(v)
        if s != 0:
            u = v / s
            R -= 2 * np.dot(u, np.dot(u.T, R))
            Q -= 2 * np.dot(u, np.dot(u.T, Q))
    #Q = Q.T
    return R.diagonal(), Q.T

In [9]:
from sklearn import datasets
from sklearn.decomposition import PCA

iris = datasets.load_iris()
X = iris.data[:, :5]
X_reduced = PCA(n_components=4)
X_reduced.fit_transform(X)
X_reduced.explained_variance_
#this is the pca from package sklearn which is based on SVD, the result is similar to our pca function 

array([ 4.19667516,  0.24062861,  0.07800042,  0.02352514])

In [10]:
import numpy as np
X = iris.data[:, :5]
A = np.cov(X.T)

D, V = my_pca(A)
print D.round(6)
print V.round(6)

# Compare the result with the numpy calculation
eigen_value_gt, eigen_vector_gt = np.linalg.eig(A)
print eigen_value_gt.round(6)
print eigen_vector_gt.round(6)

[ 4.224841  0.242244  0.078524  0.023683]
[[-0.36159  -0.65654   0.580997  0.317255]
 [ 0.082269 -0.729712 -0.596418 -0.324094]
 [-0.856572  0.175767 -0.072524 -0.479719]
 [-0.358844  0.074706 -0.549061  0.751121]]
[ 4.224841  0.242244  0.078524  0.023683]
[[ 0.36159  -0.65654  -0.580997  0.317255]
 [-0.082269 -0.729712  0.596418 -0.324094]
 [ 0.856572  0.175767  0.072524 -0.479719]
 [ 0.358844  0.074706  0.549061  0.751121]]
